apiVersion: v1
kind: ReplicationController
metadata:
  name: fronted
  labels:
    name: fronted
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: fronted
    spec:
      containers:
      - name: 9gag
        # Replace  with your project ID or use `make template`
        image: gkhandurmz/9gag 

        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        ports:
        - containerPort: 8080